<?php

namespace AppBundle\Repository;

/**
 * ClientsGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsGroupsRepository extends AppRepository
{
}
