<?php

namespace AppBundle\Repository;

/**
 * ExternalServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalServicesRepository extends AppRepository
{
}
