<?php

namespace AppBundle\Repository;

/**
 * PriceListsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceListsRepository extends AppRepository
{
}
