<?php

namespace AppBundle\Repository;

/**
 * ServiceCatalogPricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCatalogPricesRepository extends AppRepository
{
}
