<?php

namespace AppBundle\Repository;
use AppBundle\Utils\Utils;
/**
 * ServiceOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceOrdersRepository extends AppRepository
{
   
	public function __construct($em, $class)
    {
        $this->activeFilter=false;//[ 'closed' => [ 'value' => null]];
        parent::__construct($em, $class);
    }

	public function getDic($options=[]){
        Utils::deep_array_value_set('order', $options, 'number');
        return parent::getDic($options);
    }
 
//    public function getOpened($options=[]){
//        
//        return $this->getEntities( array_replace_recursive($options, [
//            'filters' => [
//                'closed' => [ 'value' => null ],
//                'client' => [ 'value' => Utils::deep_array_value('client', $options, 0) ]
//            ]
//        ]));
//    }
    
//     protected function getQueryFields($type=''){
//         $fields=[];
//         switch($type){
// //            case 'dic':
// //                $fields=array_merge(
// //                    parent::getQueryFields($type), 
// //                    [ "concat(date_format(e.created, %Y%m%d), ' : ', e.title) as k" ]
// //                );
// //            break;
//             case 'list':
//                 $fields=array_merge(
//                     parent::getQueryFields($type), 
//                     $this->addJoinedFields('client', ['id', 'name']));
//             break;
//             default:
//                 $fields=parent::getQueryFields($type);
//         }
//         return $fields;
//     }

}
