<?php

namespace AppBundle\Repository;

/**
 * ServiceOptionsPricesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceOptionsPricesRepository extends AppRepository
{
}
