<?php

namespace AppBundle\Repository;

/**
 * ServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesRepository extends AppRepository
{
	public function __construct($em, $class)
    {
        $this->activeFilter=false;
        parent::__construct($em, $class);
    }
}
