<?php

namespace AppBundle\Repository;

/**
 * ServiceRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRequestsRepository extends AppRepository
{
}
