<?php

namespace AppBundle\Repository;

/**
 * SubcontractorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcontractorsRepository extends AppRepository
{

    public function getDic($options=[]){
        Utils::deep_array_value_set('order', $options, 'name');
        return parent::getDic($options);
    }

}