client_users:
    path:     /
    defaults: { _controller: "AppBundle:Users:index" }

client_users_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Users:show" }

client_users_new:
    path:     /new
    defaults: { _controller: "AppBundle:Users:new" }

client_users_create:
    path:     /create
    defaults: { _controller: "AppBundle:Users:create" }
    methods:  POST

client_users_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Users:edit" }

client_users_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Users:update" }
    methods:  [POST, PUT]

client_users_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Users:delete" }
    methods:  [POST, DELETE]

client_users_ajax:
    path:     /ajax
    defaults: { _controller: "AppBundle:Users:ajaxList" }

client_users_dic:
    path:     /dic
    defaults: { _controller: "AppBundle:Users:ajaxDic" }

client_users_data:
    path:     /{id}/data
    defaults: { _controller: "AppBundle:Users:ajaxData" }
