app_admin_contracts:
    path:     /
    defaults: { _controller: AppBundle\Controller\ContractsController::indexAction }

app_admin_contracts_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle\Controller\ContractsController::ajaxListAction }

app_admin_contracts_create:
    path:     /create
    defaults: { _controller: AppBundle\Controller\ContractsController::createAction }
    methods:  POST

app_admin_contracts_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle\Controller\ContractsController::deleteAction }

app_admin_contracts_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle\Controller\ContractsController::editAction }

app_admin_contracts_new:
    path:     /new
    defaults: { _controller: AppBundle\Controller\ContractsController::newAction }

app_admin_contracts_remove:
    path:     /{id}/remove
    defaults: { _controller: AppBundle\Controller\ContractsController::removeAction }
    methods:  [POST, DELETE]

app_admin_contracts_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle\Controller\ContractsController::showAction }

app_admin_contracts_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle\Controller\ContractsController::updateAction }
    methods:  [POST, PUT]
