app_admin_servicecatalog:
    path:     /
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::indexAction }

app_admin_servicecatalog_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::ajaxListAction }

app_admin_servicecatalog_client_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::ajaxListAction }

app_admin_servicecatalog_create:
    path:     /create
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::createAction }
    methods:  POST

app_admin_servicecatalog_data:
    path:     /{id}/data
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::ajaxDataAction }

app_admin_servicecatalog_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::deleteAction }

app_admin_servicecatalog_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::editAction }

app_admin_servicecatalog_new:
    path:     /new
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::newAction }

app_admin_servicecatalog_remove:
    path:     /{id}/remove
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::removeAction }
    methods:  [POST, DELETE]

app_admin_servicecatalog_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::showAction }

app_admin_servicecatalog_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle\Controller\ServiceCatalogController::updateAction }
    methods:  [POST, PUT]
