app_admin_serviceorders:
    path:     /
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::indexAction }

app_admin_serviceorders_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::ajaxListAction }

app_admin_serviceorders_dic:
    path:     /dic
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::ajaxDicAction }

app_admin_serviceorders_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::showAction }

app_admin_serviceorders_data:
    path:     /{id}/data
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::ajaxDataAction }    

app_admin_serviceorders_new:
    path:     /new
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::newAction }

app_admin_serviceorders_create:
    path:     /create
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::createAction }
    methods:  POST

app_admin_serviceorders_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::editAction }

app_admin_serviceorders_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::updateAction }
    methods:  [POST, PUT]

app_admin_serviceorders_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::deleteAction }

app_admin_serviceorders_remove:
    path:     /{id}/remove
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::removeAction }
    methods:  [POST, DELETE]

app_admin_serviceorders_client:
    path:     /{cid}/client
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::indexAction }

app_admin_serviceorders_client_ajax:
    path:     /{cid}/client/ajax
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::clientAjaxListAction }

app_admin_serviceorders_client_show:
    path:     /{cid}/client/{id}/show
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::showAction }

app_admin_serviceorders_client_data:
    path:     /{cid}/client/{id}/data
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::ajaxDataAction }    

app_admin_serviceorders_client_new:
    path:     /{cid}/client/new
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::newAction }

app_admin_serviceorders_client_create:
    path:     /{cid}/client/create
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::createAction }
    methods:  POST

app_admin_serviceorders_client_edit:
    path:     /{cid}/client/{id}/edit
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::editAction }

app_admin_serviceorders_client_update:
    path:    /{cid}/client/{id}/update
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::updateAction }
    methods:  [POST, PUT]

app_admin_serviceorders_client_delete:
    path:     /{cid}/client/{id}/delete
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::deleteAction }

app_admin_serviceorders_client_remove:
    path:     /{cid}/client/{id}/remove
    defaults: { _controller: AppBundle\Controller\ServiceOrdersController::removeAction }
    methods:  [POST, DELETE]
