app_admin_users:
    path:     /
    defaults: { _controller: AppBundle\Controller\UsersController::indexAction }

app_admin_users_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle\Controller\UsersController::showAction }

app_admin_users_new:
    path:     /new
    defaults: { _controller: AppBundle\Controller\UsersController::newAction }

app_admin_users_create:
    path:     /create
    defaults: { _controller: AppBundle\Controller\UsersController::createAction }
    methods:  POST

app_admin_users_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle\Controller\UsersController::editAction }

app_admin_users_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle\Controller\UsersController::updateAction }
    methods:  [POST, PUT]

app_admin_users_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle\Controller\UsersController::deleteAction }
    methods:  [POST, DELETE]

app_admin_users_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle\Controller\UsersController::ajaxListAction }

app_admin_users_dic:
    path:     /dic
    defaults: { _controller: AppBundle\Controller\UsersController::ajaxDicAction }

app_admin_users_data:
    path:     /{id}/data
    defaults: { _controller: AppBundle\Controller\UsersController::ajaxDataAction }

app_admin_users_client:
    path:     /{cid}/index
    defaults: { _controller: AppBundle\Controller\UsersController::panelIndexAction }

app_admin_users_client_ajax:
    path:     /{cid}/ajax
    defaults: { _controller: AppBundle\Controller\UsersController::ajaxDataAction }

app_admin_users_client_new:
    path:     /{cid}/new
    defaults: { _controller: AppBundle\Controller\UsersController::newAction }

app_admin_users_client_create:
    path:     /{cid}/create
    defaults: { _controller: AppBundle\Controller\UsersController::createAction }
    methods:  POST
