app_admin_usergroups:
    path:     /
    defaults: { _controller: AppBundle\Controller\UserGroupsController::indexAction }

app_admin_usergroups_ajax:
    path:     /ajax
    defaults: { _controller: AppBundle\Controller\UserGroupsController::ajaxListAction }

app_admin_usergroups_create:
    path:     /create
    defaults: { _controller: AppBundle\Controller\UserGroupsController::createAction }
    methods:  POST

app_admin_usergroups_data:
    path:     /{id}/data
    defaults: { _controller: AppBundle\Controller\UserGroupsController::ajaxDataAction }

app_admin_usergroups_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle\Controller\UserGroupsController::deleteAction }

app_admin_usergroups_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle\Controller\UserGroupsController::editAction }

app_admin_usergroups_new:
    path:     /new
    defaults: { _controller: AppBundle\Controller\UserGroupsController::newAction }

app_admin_usergroups_remove:
    path:     /{id}/remove
    defaults: { _controller: AppBundle\Controller\UserGroupsController::removeAction }
    methods:  [POST, DELETE]

app_admin_usergroups_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle\Controller\UserGroupsController::showAction }

app_admin_usergroups_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle\Controller\UserGroupsController::updateAction }
    methods:  [POST, PUT]


