AppBundle\Entity\Users:
    type: entity
    repositoryClass: AppBundle\Repository\UsersRepository
    table: Users
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
#    fields:
#        name:
#            type: string
#            length: 45
#            nullable: true
    oneToMany:
        serviceRequests:
            targetEntity: ServiceRequests
            mappedBy: user

    manyToMany:
        userGroups:
            targetEntity: UsersGroups
            inversedBy: users
            joinTable:
                name: Users_UsersGroups
                joinColumns:
                    users_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    usersGroups_id:
                        referencedColumnName: id 
        clients:
            targetEntity: Clients
            inversedBy: users
            joinTable:
                name: Users_Clients
                joinColumns:
                    users_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    clients_id:
                        referencedColumnName: id                
            cascade: [ persist ]
        settings:
            targetEntity: Settings
            joinTable:
                name: Users_Settings
                joinColumns:
                    users_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    settings_id:
                        referencedColumnName: id 
            cascade: [ persist, remove ]

        notes:
            targetEntity: Notes
            joinTable:
                name: Users_Notes
                joinColumns:
                    users_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    notes_id:
                        referencedColumnName: id 
            cascade: [ persist, remove ]

    lifecycleCallbacks: {  }
